### ISSUE TITLE
Include the student showcase instructions on the main site?

### ISSUE THREAD

**Issue by ncoghlan** [glasnt/2018.pycon-au.org#14]
At the moment, the draft student showcase instructions linked from the application form are held in a Google doc.

Before the Student Showcase CFP is officially opened and the application form starts being publicised, it would be nice to be able to migrate those instructions into a page on the main site, so we can give it a nice URL, and a similar look-and-feel to the main CFP (but not so similar that they can get confused with each other!)

(/cc @nickyringland @hogesonline)

**Comment by glasnt** [comment]
That draft link has been removed, fyi. 

If the Showcase CFP is going to be a Google Doc we won't be able to make it the same as the main CFP; we can add copy to the site, but we just can't integrate the CFPs

**Comment by ncoghlan** [comment]
Sorry, my original comment was unclear because there are three things in draft at the moment:

- the Student Showcase submission guide (which is currently a draft in Google Docs, but should be moved to a page on the PyCon AU site before we open the Student Showcase for applications)
- the Student Showcase submission form (which will remain a Google Form, but still shouldn't be announced yet, due to the guide still being in development)
- the main CFP page (which had a link to the form, which we're not ready for yet - that's been fixed by removing the link)

We can make a PR to add the Student Showcase submission guide, so I think the main questions here would be:

1. Is there a preferred place for us to add a general information page for the Education Seminar, and describe the Student Showcase concept with a link to the submission guide?
2. Does the phrase "Student Showcase submission guide" sound like a reasonable way to help minimise the risk of confusion with the main conference CFP?

**Comment by glasnt** [comment]
1. A link in speak to  something like /speak/showcase would work
2. That phrase seems fine

The /speak page just has a teaser link for now. Submit a PR when you're ready. I'm also available on email if you have more detailed questions.

**Comment by ncoghlan** [comment]
Thanks, we'll run with that! :)
